services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  smtp4dev:
    image: rnwood/smtp4dev:3.1.3-ci20220418101
    restart: always
    ports:
      - '5001:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev
volumes:
  smtp4dev-data:
  db:
    driver: local
